#############################################################################
# Makefile for building: 1025test2
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Nov 30 20:27:59 2015
# Project:  1025test2.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile 1025test2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_imgproc.so -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mydlg1.cpp \
		mydlg2.cpp \
		mydlg3.cpp \
		mydlg4.cpp \
		mydlg5.cpp \
		mydlg6.cpp \
		mydlg7.cpp \
		mydlg8.cpp \
		mydlg9.cpp \
		mydlg10.cpp \
		dialogct.cpp \
		v4l2grab.cpp \
		handfinder.cpp \
		ct.cpp \
		convert.cpp \
		compressivetracker.cpp \
		define.cpp moc_mainwindow.cpp \
		moc_mydlg1.cpp \
		moc_mydlg2.cpp \
		moc_mydlg3.cpp \
		moc_mydlg4.cpp \
		moc_mydlg5.cpp \
		moc_mydlg6.cpp \
		moc_mydlg7.cpp \
		moc_mydlg8.cpp \
		moc_mydlg9.cpp \
		moc_mydlg10.cpp \
		moc_dialogct.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mydlg1.o \
		mydlg2.o \
		mydlg3.o \
		mydlg4.o \
		mydlg5.o \
		mydlg6.o \
		mydlg7.o \
		mydlg8.o \
		mydlg9.o \
		mydlg10.o \
		dialogct.o \
		v4l2grab.o \
		handfinder.o \
		ct.o \
		convert.o \
		compressivetracker.o \
		define.o \
		moc_mainwindow.o \
		moc_mydlg1.o \
		moc_mydlg2.o \
		moc_mydlg3.o \
		moc_mydlg4.o \
		moc_mydlg5.o \
		moc_mydlg6.o \
		moc_mydlg7.o \
		moc_mydlg8.o \
		moc_mydlg9.o \
		moc_mydlg10.o \
		moc_dialogct.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		1025test2.pro
QMAKE_TARGET  = 1025test2
DESTDIR       = 
TARGET        = 1025test2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_mydlg1.h ui_mydlg2.h ui_mydlg3.h ui_mydlg4.h ui_mydlg5.h ui_mydlg6.h ui_mydlg7.h ui_mydlg8.h ui_mydlg9.h ui_mydlg10.h ui_dialogct.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 1025test2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile 1025test2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile 1025test2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/1025test21.0.0 || $(MKDIR) .tmp/1025test21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/1025test21.0.0/ && $(COPY_FILE) --parents mainwindow.h mydlg1.h mydlg2.h mydlg3.h mydlg4.h mydlg5.h mydlg6.h mydlg7.h mydlg8.h mydlg9.h mydlg10.h dialogct.h v4l2grab.h handfinder.h define.h ct.h convert.h compressivetracker.h .tmp/1025test21.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp mydlg1.cpp mydlg2.cpp mydlg3.cpp mydlg4.cpp mydlg5.cpp mydlg6.cpp mydlg7.cpp mydlg8.cpp mydlg9.cpp mydlg10.cpp dialogct.cpp v4l2grab.cpp handfinder.cpp ct.cpp convert.cpp compressivetracker.cpp define.cpp .tmp/1025test21.0.0/ && $(COPY_FILE) --parents mainwindow.ui mydlg1.ui mydlg2.ui mydlg3.ui mydlg4.ui mydlg5.ui mydlg6.ui mydlg7.ui mydlg8.ui mydlg9.ui mydlg10.ui dialogct.ui .tmp/1025test21.0.0/ && (cd `dirname .tmp/1025test21.0.0` && $(TAR) 1025test21.0.0.tar 1025test21.0.0 && $(COMPRESS) 1025test21.0.0.tar) && $(MOVE) `dirname .tmp/1025test21.0.0`/1025test21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/1025test21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_mydlg1.cpp moc_mydlg2.cpp moc_mydlg3.cpp moc_mydlg4.cpp moc_mydlg5.cpp moc_mydlg6.cpp moc_mydlg7.cpp moc_mydlg8.cpp moc_mydlg9.cpp moc_mydlg10.cpp moc_dialogct.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mydlg1.cpp moc_mydlg2.cpp moc_mydlg3.cpp moc_mydlg4.cpp moc_mydlg5.cpp moc_mydlg6.cpp moc_mydlg7.cpp moc_mydlg8.cpp moc_mydlg9.cpp moc_mydlg10.cpp moc_dialogct.cpp
moc_mainwindow.cpp: mydlg1.h \
		mydlg2.h \
		mydlg3.h \
		mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h \
		mainwindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_mydlg1.cpp: mydlg1.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg1.h -o moc_mydlg1.cpp

moc_mydlg2.cpp: mydlg2.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg2.h -o moc_mydlg2.cpp

moc_mydlg3.cpp: mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h \
		mydlg3.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg3.h -o moc_mydlg3.cpp

moc_mydlg4.cpp: mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg4.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg4.h -o moc_mydlg4.cpp

moc_mydlg5.cpp: mydlg5.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg5.h -o moc_mydlg5.cpp

moc_mydlg6.cpp: mydlg6.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg6.h -o moc_mydlg6.cpp

moc_mydlg7.cpp: mydlg8.h \
		mydlg7.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg7.h -o moc_mydlg7.cpp

moc_mydlg8.cpp: mydlg8.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg8.h -o moc_mydlg8.cpp

moc_mydlg9.cpp: mydlg9.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg9.h -o moc_mydlg9.cpp

moc_mydlg10.cpp: mydlg10.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mydlg10.h -o moc_mydlg10.cpp

moc_dialogct.cpp: dialogct.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) dialogct.h -o moc_dialogct.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_mydlg1.h ui_mydlg2.h ui_mydlg3.h ui_mydlg4.h ui_mydlg5.h ui_mydlg6.h ui_mydlg7.h ui_mydlg8.h ui_mydlg9.h ui_mydlg10.h ui_dialogct.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_mydlg1.h ui_mydlg2.h ui_mydlg3.h ui_mydlg4.h ui_mydlg5.h ui_mydlg6.h ui_mydlg7.h ui_mydlg8.h ui_mydlg9.h ui_mydlg10.h ui_dialogct.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_mydlg1.h: mydlg1.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg1.ui -o ui_mydlg1.h

ui_mydlg2.h: mydlg2.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg2.ui -o ui_mydlg2.h

ui_mydlg3.h: mydlg3.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg3.ui -o ui_mydlg3.h

ui_mydlg4.h: mydlg4.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg4.ui -o ui_mydlg4.h

ui_mydlg5.h: mydlg5.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg5.ui -o ui_mydlg5.h

ui_mydlg6.h: mydlg6.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg6.ui -o ui_mydlg6.h

ui_mydlg7.h: mydlg7.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg7.ui -o ui_mydlg7.h

ui_mydlg8.h: mydlg8.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg8.ui -o ui_mydlg8.h

ui_mydlg9.h: mydlg9.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg9.ui -o ui_mydlg9.h

ui_mydlg10.h: mydlg10.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mydlg10.ui -o ui_mydlg10.h

ui_dialogct.h: dialogct.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic dialogct.ui -o ui_dialogct.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		mydlg1.h \
		mydlg2.h \
		mydlg3.h \
		mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mydlg1.h \
		mydlg2.h \
		mydlg3.h \
		mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mydlg1.o: mydlg1.cpp mydlg1.h \
		ui_mydlg1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg1.o mydlg1.cpp

mydlg2.o: mydlg2.cpp mydlg2.h \
		ui_mydlg2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg2.o mydlg2.cpp

mydlg3.o: mydlg3.cpp mydlg3.h \
		mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h \
		ui_mydlg3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg3.o mydlg3.cpp

mydlg4.o: mydlg4.cpp mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		ui_mydlg4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg4.o mydlg4.cpp

mydlg5.o: mydlg5.cpp mydlg5.h \
		ui_mydlg5.h \
		dialogct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg5.o mydlg5.cpp

mydlg6.o: mydlg6.cpp mydlg6.h \
		ui_mydlg6.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg6.o mydlg6.cpp

mydlg7.o: mydlg7.cpp mydlg7.h \
		mydlg8.h \
		ui_mydlg7.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg7.o mydlg7.cpp

mydlg8.o: mydlg8.cpp mydlg8.h \
		ui_mydlg8.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg8.o mydlg8.cpp

mydlg9.o: mydlg9.cpp mydlg9.h \
		ui_mydlg9.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg9.o mydlg9.cpp

mydlg10.o: mydlg10.cpp mydlg10.h \
		ui_mydlg10.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydlg10.o mydlg10.cpp

dialogct.o: dialogct.cpp dialogct.h \
		ui_dialogct.h \
		define.h \
		compressivetracker.h \
		v4l2grab.h \
		convert.h \
		handfinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogct.o dialogct.cpp

v4l2grab.o: v4l2grab.cpp define.h \
		compressivetracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v4l2grab.o v4l2grab.cpp

handfinder.o: handfinder.cpp define.h \
		compressivetracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handfinder.o handfinder.cpp

ct.o: ct.cpp compressivetracker.h \
		handfinder.h \
		define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ct.o ct.cpp

convert.o: convert.cpp define.h \
		compressivetracker.h \
		v4l2grab.h \
		mainwindow.h \
		mydlg1.h \
		mydlg2.h \
		mydlg3.h \
		mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o convert.o convert.cpp

compressivetracker.o: compressivetracker.cpp compressivetracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compressivetracker.o compressivetracker.cpp

define.o: define.cpp mainwindow.h \
		mydlg1.h \
		mydlg2.h \
		mydlg3.h \
		mydlg4.h \
		mydlg6.h \
		mydlg7.h \
		mydlg8.h \
		mydlg9.h \
		mydlg10.h \
		mydlg5.h \
		dialogct.h \
		define.h \
		compressivetracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o define.o define.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mydlg1.o: moc_mydlg1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg1.o moc_mydlg1.cpp

moc_mydlg2.o: moc_mydlg2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg2.o moc_mydlg2.cpp

moc_mydlg3.o: moc_mydlg3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg3.o moc_mydlg3.cpp

moc_mydlg4.o: moc_mydlg4.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg4.o moc_mydlg4.cpp

moc_mydlg5.o: moc_mydlg5.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg5.o moc_mydlg5.cpp

moc_mydlg6.o: moc_mydlg6.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg6.o moc_mydlg6.cpp

moc_mydlg7.o: moc_mydlg7.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg7.o moc_mydlg7.cpp

moc_mydlg8.o: moc_mydlg8.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg8.o moc_mydlg8.cpp

moc_mydlg9.o: moc_mydlg9.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg9.o moc_mydlg9.cpp

moc_mydlg10.o: moc_mydlg10.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydlg10.o moc_mydlg10.cpp

moc_dialogct.o: moc_dialogct.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogct.o moc_dialogct.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

